# Generated by Django 4.0.4 on 2022-05-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(blank=True, unique=True)),
                ('short_url', models.CharField(blank=True, max_length=35, unique=True)),
            ],
        ),
    ]
